title: Allen Close
logo: /assets/img/headshot circle.png
description: SQL Server · Power BI · Advanced Excel · Python (Learning) | Focused on transforming data into actionable business insights
show_downloads: false
theme: jekyll-theme-minimal
